### ISSUE TITLE
404错误呀！

### ISSUE THREAD

**Issue by linkjek** [lvr1997/kd-second-hand-workshop#12]
运行了项目但是404错误
![屏幕截图 2020-11-11 151255](https://user-images.githubusercontent.com/54795416/98813736-a560a700-245f-11eb-8299-0d1e51f1305f.png)
![image](https://user-images.githubusercontent.com/54795416/98813811-c88b5680-245f-11eb-8f34-b870964d2df8.png)

**Comment by lvr1997** [comment]
项目与Tomcat9不兼容，最新提交的版本可以兼容Tomcat8及Tomcat8.5
