### ISSUE TITLE
【科大二手工坊】项目遇到的问题和建议

### ISSUE THREAD

**Issue by lvr1997** [lvr1997/kd-second-hand-workshop#19]
1. 首先感谢各位小伙伴们的支持！
2. 项目上遇到任何问题或对项目有什么建议，都可以在这里提出来哦
3. 关于功能更新方面，1.0版本不会再新增功能，目前正在开发的[科大二手工坊V2.0版本](https://github.com/lvr1997/kd-shop-web)会实现，关于2.0版本的建议也可以提在这里哦

**Comment by lvr1997** [comment]
## 启动项目

1. 使用IDEA打开项目

2. 编辑Tomcat配置

![QQ截图20211218171208.png](https://s2.loli.net/2021/12/18/UJR5dW6LDYjvIbt.png)

3. 配置Tomcat路径、jre环境、端口号

![QQ图片20211218171636.png](https://s2.loli.net/2021/12/18/H28jI7PM5yvNUAL.png)

4. 将项目war包添加至tomcat中

![QQ图片20211218172006.png](https://s2.loli.net/2021/12/18/RveWbpOrSstMgUi.png)

5. 在你的`tomcat`中建立`images`文件夹

![image.png](https://s2.loli.net/2021/12/20/qjlAst3E58JP9u6.png)

6. 在idea中配置images图片资源目录

![image.png](https://s2.loli.net/2021/12/20/qjlAst3E58JP9u6.png)

7. 选择刚刚在tomcat中建立的文件夹，点击ok

 ![images](https://s2.loli.net/2021/12/20/ZNocujMeFawLfqd.png)
 
8. 

![image.png](https://s2.loli.net/2021/12/20/qjlAst3E58JP9u6.png)

9. 启动项目访问网址：localhost:8088/goods/index

**Comment by Windsky-00** [comment]
请问这个项目能否搭载到互联网服务器上

**Comment by lvr1997** [comment]
> 第4步这个war包在哪儿呢

您好，可以加Q，群文件有详细的部署视频

**Comment by lvr1997** [comment]
> 请问这个项目能否搭载到互联网服务器上

您好，这个我没有尝试过，理论上是可以的。

**Comment by Dashing1105** [comment]
请问为什么加载不出来图片资源？

**Comment by lvr1997** [comment]
> 请问为什么加载不出来图片资源？

您好，可能的原因是项目没有部署好，检查images文件夹的映射位置。若还是不行，QQ群内有视频教程

**Comment by muyuningyu** [comment]
你好，eclipse上怎么启动呀，用不了呢

**Comment by muyuningyu** [comment]
怎么连接数据库呀，没看到JDBCdriver呢

**Comment by muyuningyu** [comment]
![VVA3)_J`_COKOHKB`O5C{WP](https://user-images.githubusercontent.com/103873800/163715726-3d72f985-4c60-4f9b-9ce2-8c77421353dd.png)

**Comment by lvr1997** [comment]
> ![VVA3)_J_COKOHKBO5C{WP](https://user-images.githubusercontent.com/103873800/163715726-3d72f985-4c60-4f9b-9ce2-8c77421353dd.png)

就是这个文件，只需要把用户名密码等信息改成自己的即可

**Comment by JM0011** [comment]
你好，我加了群一直没有同意，可以让我加下群嘛，我想看下部署视频，一直没成功

**Comment by chan3301** [comment]
> 你好，你解决这个问题没有？

**Comment by chan3301** [comment]
你好，可以通过下qq群吗？

**Comment by luoyefenfei-oss** [comment]
你好，可以通过下qq群吗？

**Comment by jieffliu** [comment]
您好，可以通过下qq群吗

**Comment by lzkasa** [comment]
你好，运行显示404怎么搞啊

**Comment by duc-123** [comment]
大佬可以通过一下qq群吗

**Comment by yumiaojing** [comment]
还删我评论，你拿了我的钱，可是项目现在是有问题的，那你还我钱

**Comment by yumiaojing** [comment]
作者删评论
![github](https://github.com/user-attachments/assets/ace1509f-05e4-45f0-97be-5847bfc1aff0)

**Comment by yumiaojing** [comment]
还钱

**Comment by yumiaojing** [comment]
还钱

**Comment by yumiaojing** [comment]
还钱

**Comment by yumiaojing** [comment]
还钱

**Comment by yumiaojing** [comment]
还钱

**Comment by yumiaojing** [comment]
还钱我20块

**Comment by lvr1997** [comment]
🐶



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lvr1997/kd-second-hand-workshop] 【科大二手工坊】项目遇到的问题和建议 (Issue #19)




 
jian人

**Comment by yumiaojing** [comment]
🐕 娘养的 chu生

**Comment by lvr1997** [comment]
不想跟你这sb一般见识，辣🐔



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 晚上9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lvr1997/kd-second-hand-workshop] 【科大二手工坊】项目遇到的问题和建议 (Issue #19)




 
🐕 娘养的 chu生

**Comment by luoyefenfei-oss** [comment]
你是不是搞错了，我不是管理员，也没收你钱。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 晚上9:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lvr1997/kd-second-hand-workshop] 【科大二手工坊】项目遇到的问题和建议 (Issue #19)




 真TM后悔帮你 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年12月2日(周一) 晚上9:34 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [lvr1997/kd-second-hand-workshop] 【科大二手工坊】项目遇到的问题和建议 (Issue #19) 
 
 
 
 
   
 🐕 娘养的 chu生
