### ISSUE TITLE
救命求助

### ISSUE THREAD

**Issue by muyuningyu** [lvr1997/kd-second-hand-workshop#25]
怎么连接数据库啊，是需要自己写JBDCutile吗。Q群加不进去

**Comment by muyuningyu** [comment]
![image](https://user-images.githubusercontent.com/103873800/163720704-fe57cf22-b84a-466e-9264-e565a39a5d77.png)
登录不了这样报错该怎么解决呀

**Comment by lvr1997** [comment]
数据库相关配置在/src/main/resources/jdbc.properties 文件修改，q群可以添加的696224249
